### ISSUE TITLE
Position Type : Float not work

### ISSUE THREAD

**Issue by eripahle** [SIMITGROUP/phpjasperxml#11]
sample1.jrxml work properly nice one, I tried to edit Page Header Band in sampple1.jrxml with some of 
1. TextField with "stretch with overflow" parameter = true (iReport5.1.0), so the height of component is base of value inside.
2. and in the bottom of that textFiled I put some StaticText with "Position Type" parameter = Float

normaly : in jasper report perspective , StaticText will appeare relatively after TextFiled (Bottom), but in my case with phpjasperxml, StaticText appeared fixed (overwrite view of TextField)

Q:
1. there are still bugs in this version (1.0) about stretch with overflow and floating component?
or there are any suggest how to implement stretch with overflow and floating component in phpjasperxml?

thnkst for the library :),

**Comment by kstan79** [comment]
phpjasperxml currently not support position type parameter, to support it i believe there is great challenges. Basically we need to overcome:
1. know the total band height
2. cater band expand to next page and y position need to realign
3. might need to change upstream tcpdf multicell behaviour
4. figure a way to measure current text field total height according content/fonts size, then adjust the positioning again.
5. there is others effect but i cant imagine yet.
6. this constraint happen in sub report too, we can shrink content in detail band nicely due to similar challenges.  


Since begining phpjasperxml design as a simple wysiwyg report library, and we decided to support basic use option. from time to time features added to support jasperreport, however some special functionality is hard to implement due to initial design we can't foresee the requirement. 

If there is any expert can patch this then can help a lot of people.

**Comment by kstan79** [comment]
i forget to mention, you can concat both textbox value by this method. Currently we do as below.

> $F{item_code}+' - '+${item_name} +"\n"+$F{remark}
