### ISSUE TITLE
./class/pchart2/cache is not writable for generate chart, please contact software developer or system adminstrator

### ISSUE THREAD

**Issue by kiranugale** [SIMITGROUP/phpjasperxml#22]
I create one report in that report I take only one chart and try to open in a browser I found above error.
for more information please check my attached files.
[reports.zip](https://github.com/SIMITGROUP/phpjasperxml/files/2459165/reports.zip)

![image](https://user-images.githubusercontent.com/19143501/46651462-baeaaf00-cbbd-11e8-8edd-594f3606d964.png)

**Comment by kstan79** [comment]
seems answer very obvious, make your folder ./class/pchart2/cache writable

**Comment by kiranugale** [comment]
I tried to search that folder/class/pchart2/cache
but it's not found. 
only I found this one phpjasper7.2\pchart2\class  and its already have permission.

**Comment by kiranugale** [comment]
i check all folder permission i can read and write in phchart2 folder also i can delete file.

**Comment by kstan79** [comment]
ya, ya, ya. Latest structure break chart and export excel library. Let me fix it. will update soon. Thanks!

**Comment by kstan79** [comment]
the new structure now support basic line chart, barchart and pie chart. It shall render chart in pdf but don't expect it look beautiful. What I did is only separate out chart into dedicated class, and perform some house keeping. The chart renderer still using pchart2 and lot of option in jasper report is not supported yet. We hope there is community help us in this area, since at production we not use pdf draw chart.

**Comment by kiranugale** [comment]
Thanks !!!!!!!!!!!!!!!!!!!!!!!!!
