### ISSUE TITLE
Warning when composer require

### ISSUE THREAD

**Issue by mohamadyuzrie** [SIMITGROUP/phpjasperxml#47]
I found out that this package exist on packagist, so I went ahead and did `composer require composer require simitgroup/phpjasperxml`. However, I get warning for ambiguous file found on vendor. I've attached a screenshot that shows that.

![Ambiguous class](https://user-images.githubusercontent.com/51981484/61939292-82d62080-afc5-11e9-8d11-b16468a64dbb.PNG)

One of the line goes like this:
```bash
Warning: Ambiguous class resolution, "pChart\pDraw" was found in both "...vendor/simitgroup/phpjasperxml\pchart2\pChart\pDraw.debug.php" and "...vendor/simitgroup/phpjasperxml\pchart2\pChart\pDraw.php", the first will be used.
```

**Comment by kstan79** [comment]
hi, phpjasperxml at the moment have obvious issue cause parallel 1.0 and 1.1 exists in the repository, the reason is some jrxml not compatible with 1.1 that why we have to maintain both active. That will cause composer failed. You may put phpjasperxml in some folder and include with convensional method 'include' or 'include_once'.
